
// const str = 'kranthi';
// console.log(str.at(0));
// console.log(str.anchor(5));
// console.log(str.big());
// console.log(str.blink());
// console.log(str.bold(5));
// console.log(str.charAt(5));
// console.log(str.charCodeAt(1));
// console.log(str.codePointAt(5));
// console.log(str.concat(5));
// console.log(str.constructor(1));
// console.log(str.endsWith('i'));
// console.log(str.endsWith());
// console.log(str.includes(''));
// console.log(str.includes(''));
// console.log(str.indexOf('t'));
// console.log(str.italics());
// console.log(str.fixed());
// console.log(str.fontcolor('green'));
// console.log(str.fontsize('15px'));
// console.log(str.isWellFormed());
// console.log(str.lastIndexOf(''));
// console.log(str.lastIndexOf('x'));
// console.log(str.lastIndexOf('kranthi'));
// console.log(str.lastIndexOf(str));
// console.log(str.link(str));
// console.log(str.localeCompare(''));
// console.log(str.localeCompare('d'));
// console.log(str.localeCompare(str));
// console.log(str.localeCompare('kranthi'));
// console.log(str.match(1));
// console.log(str.match('kranthi'));
// console.log(str.match());
// console.log(str.matchAll(1));
// console.log(str.matchAll());
// console.log(str.normalize());
// console.log(str.padEnd(10));
// console.log(str.padEnd(10, '3'));
// console.log(str.padStart());
// console.log(str.repeat('kranthi'));
// console.log(str.repeat(3));
// console.log(str.replace());
// console.log(str.replace(''));
// console.log(str.replace('kranthi'));
// console.log(str.replaceAll(''));
// console.log(str.replaceAll(1));
// console.log(str.search('k'));
// console.log(str.search(''));
// console.log(str.search(1));
// console.log(str.slice(3));
// console.log(str.split('kranthi'));
// console.log(str.split(''));
// console.log(str.split());
// console.log(str.small());
// console.log(str.startsWith(''));
// console.log(str.startsWith());
// console.log(str.strike());
// console.log(str.sub());
// console.log(str.substr());
// console.log(str.substring());
// console.log(str.sup());
// console.log(str.toLocaleLowerCase());
// console.log(str.toLocaleUpperCase());
// console.log(str.toUpperCase());
// console.log(str.toLowerCase());
// console.log(str.toWellFormed());
// console.log(str.trim());
// console.log(str.valueOf('k'));
// console.log(str.valueOf(1));
// console.log(str);

// console.log(String.prototype);



